---

- name: install heartbeat
  vars:
    packages:
      - heartbeat
  apt:
    name: "{{ packages }}"
    state: "present"

- name: stop service heartbeat before configuration
  systemd:
    state: stopped
    name: heartbeat

- name: ensure heartbeat authkeys file
  template: src="authkeys.j2" dest=/etc/ha.d/authkeys mode=0600
  notify:
    - restart heartbeat

- name: ensure heartbeat ha.cf file
  template: src="ha.cf.j2" dest=/etc/ha.d/ha.cf mode=0644
  notify:
    - restart heartbeat

- name: ensure heartbeat haresources file
  template: src="haresources.j2" dest=/etc/ha.d/haresources mode=0644
  notify:
    - restart heartbeat
